### ISSUE TITLE
Control the size of the image

### ISSUE THREAD

**Issue by LYTWilson** [amatya-aditya/obsidian-media-slider#3]
Another little issue that I found is about the image size. In general, we would be able to control the image size by ![Freud's Psyche Iceberg|300](a website), or [[hello.png|200]], which I found is not possible in the image-slider. The plugin is great work, the issue is not to blame or hurry anything, just something that could be seen and put into the roadmap.

**Comment by jmonroynieto** [comment]
As a workaround, I use this snipped to change the size of all images.

```css
[class^="block-language-image-slider"] .gallery_wrapper ul.inner-slider li.img-card {
    width: 55%; /* crude change */
}
``` 

I'm interested in helping implement this. I don't quite know whether your suggestion is optimal from user experience. I'd like to understand how image-individual controls would help you, please elaborate your use case. The only time I have seen height-uneven sliders was the finder carousel in macOS; and that was to retain width of the element. 

 From my workflow, I sometimes just need the photos to not take  so much vertical space. I think it makes sense to give the user a height setting or the card width .
